package au.org.alfred.icu.nutrition.persistence.auto;

import java.util.Date;
import java.util.List;

import au.org.alfred.icu.kinetic.persistence.ext.PersistenceObject;
import au.org.alfred.icu.nutrition.persistence.Review;

/**
 * Class _Assesmentandplan was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Assesmentandplan extends PersistenceObject {

    public static final String ACTIVITY_FACTOR_PROPERTY = "activityFactor";
    public static final String ADJUSTED_CALC_METHOD_PROPERTY = "adjustedCalcMethod";
    public static final String ADJUSTED_WEIGHT_PROPERTY = "adjustedWeight";
    public static final String ADM_ID_PROPERTY = "admId";
    public static final String ASSESMENT_DATE_PROPERTY = "assesmentDate";
    public static final String ASSESSMENT_DIETICIAN_PROPERTY = "assessmentDietician";
    public static final String E_NCOMMENT_PROPERTY = "eNComment";
    public static final String E_NFORMULA_PROPERTY = "eNFormula";
    public static final String E_NHOURS_FEED_PROPERTY = "eNHoursFeed";
    public static final String E_NPUMP_BE_PROPERTY = "eNPumpBE";
    public static final String E_NTARGET_PROPERTY = "eNTarget";
    public static final String EQUATION_PROPERTY = "equation";
    public static final String EXTRA_PLAN_PROPERTY = "extraPlan";
    public static final String HEIGHT_CM_PROPERTY = "heightCm";
    public static final String HEIGHT_ESTIMATE_OR_ACTUAL_PROPERTY = "heightEstimateOrActual";
    public static final String HEIGHT_SOURCE_PROPERTY = "heightSource";
    public static final String I_CUADM_ID_PROPERTY = "iCUAdmId";
    public static final String ORAL_DIET_CODE_PROPERTY = "oralDietCode";
    public static final String ORAL_ESTIMATE_ENERGY_PROPERTY = "oralEstimateEnergy";
    public static final String ORAL_ESTIMATE_PROTEIN_PROPERTY = "oralEstimateProtein";
    public static final String ORAL_SUPPLEMENTS_PROPERTY = "oralSupplements";
    public static final String P_NCOMMENT_PROPERTY = "pNComment";
    public static final String P_NFORMULA_PROPERTY = "pNFormula";
    public static final String P_NHOURS_FEED_PROPERTY = "pNHoursFeed";
    public static final String P_NPUMP_BE_PROPERTY = "pNPumpBE";
    public static final String P_NTARGET_RATE_PROPERTY = "pNTargetRate";
    public static final String PROGRESS_TO_DATE_HISTORY_PROPERTY = "progressToDateHistory";
    public static final String PROTEIN_REQUIREMENT_PROPERTY = "proteinRequirement";
    public static final String REFERENCE_RANGE_PROPERTY = "referenceRange";
    public static final String RMR_PROPERTY = "rmr";
    public static final String STRESS_FACTOR_PROPERTY = "stressFactor";
    public static final String UR_PROPERTY = "ur";
    public static final String WEIGHT_PROPERTY = "weight";
    public static final String WEIGHT_ESTIMATE_OR_ACTUAL_PROPERTY = "weightEstimateOrActual";
    public static final String WEIGHT_SOURCE_PROPERTY = "weightSource";
    public static final String REVIEW_ARRAY_PROPERTY = "reviewArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setActivityFactor(Double activityFactor) {
        writeProperty("activityFactor", activityFactor);
    }
    public Double getActivityFactor() {
        return (Double)readProperty("activityFactor");
    }

    public void setAdjustedCalcMethod(String adjustedCalcMethod) {
        writeProperty("adjustedCalcMethod", adjustedCalcMethod);
    }
    public String getAdjustedCalcMethod() {
        return (String)readProperty("adjustedCalcMethod");
    }

    public void setAdjustedWeight(Long adjustedWeight) {
        writeProperty("adjustedWeight", adjustedWeight);
    }
    public Long getAdjustedWeight() {
        return (Long)readProperty("adjustedWeight");
    }

    public void setAdmId(String admId) {
        writeProperty("admId", admId);
    }
    public String getAdmId() {
        return (String)readProperty("admId");
    }

    public void setAssesmentDate(Date assesmentDate) {
        writeProperty("assesmentDate", assesmentDate);
    }
    public Date getAssesmentDate() {
        return (Date)readProperty("assesmentDate");
    }

    public void setAssessmentDietician(String assessmentDietician) {
        writeProperty("assessmentDietician", assessmentDietician);
    }
    public String getAssessmentDietician() {
        return (String)readProperty("assessmentDietician");
    }

    public void setENComment(String eNComment) {
        writeProperty("eNComment", eNComment);
    }
    public String getENComment() {
        return (String)readProperty("eNComment");
    }

    public void setENFormula(String eNFormula) {
        writeProperty("eNFormula", eNFormula);
    }
    public String getENFormula() {
        return (String)readProperty("eNFormula");
    }

    public void setENHoursFeed(Long eNHoursFeed) {
        writeProperty("eNHoursFeed", eNHoursFeed);
    }
    public Long getENHoursFeed() {
        return (Long)readProperty("eNHoursFeed");
    }

    public void setENPumpBE(String eNPumpBE) {
        writeProperty("eNPumpBE", eNPumpBE);
    }
    public String getENPumpBE() {
        return (String)readProperty("eNPumpBE");
    }

    public void setENTarget(Long eNTarget) {
        writeProperty("eNTarget", eNTarget);
    }
    public Long getENTarget() {
        return (Long)readProperty("eNTarget");
    }

    public void setEquation(String equation) {
        writeProperty("equation", equation);
    }
    public String getEquation() {
        return (String)readProperty("equation");
    }

    public void setExtraPlan(Boolean extraPlan) {
        writeProperty("extraPlan", extraPlan);
    }
    public Boolean getExtraPlan() {
        return (Boolean)readProperty("extraPlan");
    }

    public void setHeightCm(Long heightCm) {
        writeProperty("heightCm", heightCm);
    }
    public Long getHeightCm() {
        return (Long)readProperty("heightCm");
    }

    public void setHeightEstimateOrActual(Boolean heightEstimateOrActual) {
        writeProperty("heightEstimateOrActual", heightEstimateOrActual);
    }
    public Boolean getHeightEstimateOrActual() {
        return (Boolean)readProperty("heightEstimateOrActual");
    }

    public void setHeightSource(String heightSource) {
        writeProperty("heightSource", heightSource);
    }
    public String getHeightSource() {
        return (String)readProperty("heightSource");
    }

    public void setICUAdmId(String iCUAdmId) {
        writeProperty("iCUAdmId", iCUAdmId);
    }
    public String getICUAdmId() {
        return (String)readProperty("iCUAdmId");
    }

    public void setOralDietCode(String oralDietCode) {
        writeProperty("oralDietCode", oralDietCode);
    }
    public String getOralDietCode() {
        return (String)readProperty("oralDietCode");
    }

    public void setOralEstimateEnergy(Double oralEstimateEnergy) {
        writeProperty("oralEstimateEnergy", oralEstimateEnergy);
    }
    public Double getOralEstimateEnergy() {
        return (Double)readProperty("oralEstimateEnergy");
    }

    public void setOralEstimateProtein(Long oralEstimateProtein) {
        writeProperty("oralEstimateProtein", oralEstimateProtein);
    }
    public Long getOralEstimateProtein() {
        return (Long)readProperty("oralEstimateProtein");
    }

    public void setOralSupplements(String oralSupplements) {
        writeProperty("oralSupplements", oralSupplements);
    }
    public String getOralSupplements() {
        return (String)readProperty("oralSupplements");
    }

    public void setPNComment(String pNComment) {
        writeProperty("pNComment", pNComment);
    }
    public String getPNComment() {
        return (String)readProperty("pNComment");
    }

    public void setPNFormula(String pNFormula) {
        writeProperty("pNFormula", pNFormula);
    }
    public String getPNFormula() {
        return (String)readProperty("pNFormula");
    }

    public void setPNHoursFeed(Long pNHoursFeed) {
        writeProperty("pNHoursFeed", pNHoursFeed);
    }
    public Long getPNHoursFeed() {
        return (Long)readProperty("pNHoursFeed");
    }

    public void setPNPumpBE(String pNPumpBE) {
        writeProperty("pNPumpBE", pNPumpBE);
    }
    public String getPNPumpBE() {
        return (String)readProperty("pNPumpBE");
    }

    public void setPNTargetRate(Long pNTargetRate) {
        writeProperty("pNTargetRate", pNTargetRate);
    }
    public Long getPNTargetRate() {
        return (Long)readProperty("pNTargetRate");
    }

    public void setProgressToDateHistory(String progressToDateHistory) {
        writeProperty("progressToDateHistory", progressToDateHistory);
    }
    public String getProgressToDateHistory() {
        return (String)readProperty("progressToDateHistory");
    }

    public void setProteinRequirement(Double proteinRequirement) {
        writeProperty("proteinRequirement", proteinRequirement);
    }
    public Double getProteinRequirement() {
        return (Double)readProperty("proteinRequirement");
    }

    public void setReferenceRange(String referenceRange) {
        writeProperty("referenceRange", referenceRange);
    }
    public String getReferenceRange() {
        return (String)readProperty("referenceRange");
    }

    public void setRmr(Double rmr) {
        writeProperty("rmr", rmr);
    }
    public Double getRmr() {
        return (Double)readProperty("rmr");
    }

    public void setStressFactor(Double stressFactor) {
        writeProperty("stressFactor", stressFactor);
    }
    public Double getStressFactor() {
        return (Double)readProperty("stressFactor");
    }

    public void setUr(String ur) {
        writeProperty("ur", ur);
    }
    public String getUr() {
        return (String)readProperty("ur");
    }

    public void setWeight(Long weight) {
        writeProperty("weight", weight);
    }
    public Long getWeight() {
        return (Long)readProperty("weight");
    }

    public void setWeightEstimateOrActual(Boolean weightEstimateOrActual) {
        writeProperty("weightEstimateOrActual", weightEstimateOrActual);
    }
    public Boolean getWeightEstimateOrActual() {
        return (Boolean)readProperty("weightEstimateOrActual");
    }

    public void setWeightSource(String weightSource) {
        writeProperty("weightSource", weightSource);
    }
    public String getWeightSource() {
        return (String)readProperty("weightSource");
    }

    public void addToReviewArray(Review obj) {
        addToManyTarget("reviewArray", obj, true);
    }
    public void removeFromReviewArray(Review obj) {
        removeToManyTarget("reviewArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Review> getReviewArray() {
        return (List<Review>)readProperty("reviewArray");
    }


}
