package au.org.alfred.icu.nutrition.persistence.auto;

import java.util.Date;

import au.org.alfred.icu.kinetic.persistence.ext.PersistenceObject;
import au.org.alfred.icu.nutrition.persistence.Assesmentandplan;

/**
 * Class _Review was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Review extends PersistenceObject {

    public static final String AP_CERNER_PROPERTY = "apCerner";
    public static final String AP_COLOXYL_PROPERTY = "apColoxyl";
    public static final String AP_ENEMA_PROPERTY = "apEnema";
    public static final String AP_FLEET_PROPERTY = "apFleet";
    public static final String AP_GO_LYTELY_PROPERTY = "apGoLytely";
    public static final String AP_LACTULOSE_PROPERTY = "apLactulose";
    public static final String AP_MOVICOL_PROPERTY = "apMovicol";
    public static final String AP_NOT_GIVEN_PROPERTY = "apNotGiven";
    public static final String ASSESMENT_DATE_PROPERTY = "assesmentDate";
    public static final String BOWEL_ACTIONS_PROPERTY = "bowelActions";
    public static final String E_NRECIEVED_PROPERTY = "eNrecieved";
    public static final String FINE_BORE_PROPERTY = "fineBore";
    public static final String FLEXISEAL_PROPERTY = "flexiseal";
    public static final String FLEXISEAL_VOLUME_PROPERTY = "flexisealVolume";
    public static final String I_CUADM_ID_PROPERTY = "iCUAdmId";
    public static final String NUMBER_OF_GASTRIC_ASPIRATE_PROPERTY = "numberOfGastricAspirate";
    public static final String ORAL_ENERGY_RECEIVED_PROPERTY = "oralEnergyReceived";
    public static final String ORAL_PROTEIN_RECEIVED_PROPERTY = "oralProteinReceived";
    public static final String P_NRECEIVED_PROPERTY = "pNreceived";
    public static final String PK_ERYTHROMYCIN_PROPERTY = "pkErythromycin";
    public static final String PK_METOCLOPRAMIDE_PROPERTY = "pkMetoclopramide";
    public static final String PK_NONE_PROPERTY = "pkNone";
    public static final String PK_NOT_GIVEN_PROPERTY = "pkNotGiven";
    public static final String PK_OTHER_PROPERTY = "pkOther";
    public static final String PROPOFOL_PROPERTY = "propofol";
    public static final String REVIEW_COMMENT_PROPERTY = "reviewComment";
    public static final String REVIEW_DATE_PROPERTY = "reviewDate";
    public static final String REVIEW_DIETICIAN_PROPERTY = "reviewDietician";
    public static final String TOTAL_GASTRIC_APIRATE_VOLUME_PROPERTY = "totalGastricApirateVolume";
    public static final String VOMIT_PROPERTY = "vomit";
    public static final String VOMIT_VOLUME_PROPERTY = "vomitVolume";
    public static final String TO_ASSESMENTANDPLAN_PROPERTY = "toAssesmentandplan";

    public static final String ASSESMENTANDPLAN_ID_PK_COLUMN = "assesmentandplan_ID";
    public static final String ID_PK_COLUMN = "id";

    public void setApCerner(Boolean apCerner) {
        writeProperty("apCerner", apCerner);
    }
    public Boolean getApCerner() {
        return (Boolean)readProperty("apCerner");
    }

    public void setApColoxyl(Boolean apColoxyl) {
        writeProperty("apColoxyl", apColoxyl);
    }
    public Boolean getApColoxyl() {
        return (Boolean)readProperty("apColoxyl");
    }

    public void setApEnema(Boolean apEnema) {
        writeProperty("apEnema", apEnema);
    }
    public Boolean getApEnema() {
        return (Boolean)readProperty("apEnema");
    }

    public void setApFleet(Boolean apFleet) {
        writeProperty("apFleet", apFleet);
    }
    public Boolean getApFleet() {
        return (Boolean)readProperty("apFleet");
    }

    public void setApGoLytely(Boolean apGoLytely) {
        writeProperty("apGoLytely", apGoLytely);
    }
    public Boolean getApGoLytely() {
        return (Boolean)readProperty("apGoLytely");
    }

    public void setApLactulose(Boolean apLactulose) {
        writeProperty("apLactulose", apLactulose);
    }
    public Boolean getApLactulose() {
        return (Boolean)readProperty("apLactulose");
    }

    public void setApMovicol(Boolean apMovicol) {
        writeProperty("apMovicol", apMovicol);
    }
    public Boolean getApMovicol() {
        return (Boolean)readProperty("apMovicol");
    }

    public void setApNotGiven(Boolean apNotGiven) {
        writeProperty("apNotGiven", apNotGiven);
    }
    public Boolean getApNotGiven() {
        return (Boolean)readProperty("apNotGiven");
    }

    public void setAssesmentDate(Date assesmentDate) {
        writeProperty("assesmentDate", assesmentDate);
    }
    public Date getAssesmentDate() {
        return (Date)readProperty("assesmentDate");
    }

    public void setBowelActions(Long bowelActions) {
        writeProperty("bowelActions", bowelActions);
    }
    public Long getBowelActions() {
        return (Long)readProperty("bowelActions");
    }

    public void setENrecieved(Long eNrecieved) {
        writeProperty("eNrecieved", eNrecieved);
    }
    public Long getENrecieved() {
        return (Long)readProperty("eNrecieved");
    }

    public void setFineBore(Boolean fineBore) {
        writeProperty("fineBore", fineBore);
    }
    public Boolean getFineBore() {
        return (Boolean)readProperty("fineBore");
    }

    public void setFlexiseal(Boolean flexiseal) {
        writeProperty("flexiseal", flexiseal);
    }
    public Boolean getFlexiseal() {
        return (Boolean)readProperty("flexiseal");
    }

    public void setFlexisealVolume(Long flexisealVolume) {
        writeProperty("flexisealVolume", flexisealVolume);
    }
    public Long getFlexisealVolume() {
        return (Long)readProperty("flexisealVolume");
    }

    public void setICUAdmId(String iCUAdmId) {
        writeProperty("iCUAdmId", iCUAdmId);
    }
    public String getICUAdmId() {
        return (String)readProperty("iCUAdmId");
    }

    public void setNumberOfGastricAspirate(Long numberOfGastricAspirate) {
        writeProperty("numberOfGastricAspirate", numberOfGastricAspirate);
    }
    public Long getNumberOfGastricAspirate() {
        return (Long)readProperty("numberOfGastricAspirate");
    }

    public void setOralEnergyReceived(Double oralEnergyReceived) {
        writeProperty("oralEnergyReceived", oralEnergyReceived);
    }
    public Double getOralEnergyReceived() {
        return (Double)readProperty("oralEnergyReceived");
    }

    public void setOralProteinReceived(Long oralProteinReceived) {
        writeProperty("oralProteinReceived", oralProteinReceived);
    }
    public Long getOralProteinReceived() {
        return (Long)readProperty("oralProteinReceived");
    }

    public void setPNreceived(Long pNreceived) {
        writeProperty("pNreceived", pNreceived);
    }
    public Long getPNreceived() {
        return (Long)readProperty("pNreceived");
    }

    public void setPkErythromycin(Boolean pkErythromycin) {
        writeProperty("pkErythromycin", pkErythromycin);
    }
    public Boolean getPkErythromycin() {
        return (Boolean)readProperty("pkErythromycin");
    }

    public void setPkMetoclopramide(Boolean pkMetoclopramide) {
        writeProperty("pkMetoclopramide", pkMetoclopramide);
    }
    public Boolean getPkMetoclopramide() {
        return (Boolean)readProperty("pkMetoclopramide");
    }

    public void setPkNone(Boolean pkNone) {
        writeProperty("pkNone", pkNone);
    }
    public Boolean getPkNone() {
        return (Boolean)readProperty("pkNone");
    }

    public void setPkNotGiven(Boolean pkNotGiven) {
        writeProperty("pkNotGiven", pkNotGiven);
    }
    public Boolean getPkNotGiven() {
        return (Boolean)readProperty("pkNotGiven");
    }

    public void setPkOther(String pkOther) {
        writeProperty("pkOther", pkOther);
    }
    public String getPkOther() {
        return (String)readProperty("pkOther");
    }

    public void setPropofol(Long propofol) {
        writeProperty("propofol", propofol);
    }
    public Long getPropofol() {
        return (Long)readProperty("propofol");
    }

    public void setReviewComment(String reviewComment) {
        writeProperty("reviewComment", reviewComment);
    }
    public String getReviewComment() {
        return (String)readProperty("reviewComment");
    }

    public void setReviewDate(Date reviewDate) {
        writeProperty("reviewDate", reviewDate);
    }
    public Date getReviewDate() {
        return (Date)readProperty("reviewDate");
    }

    public void setReviewDietician(String reviewDietician) {
        writeProperty("reviewDietician", reviewDietician);
    }
    public String getReviewDietician() {
        return (String)readProperty("reviewDietician");
    }

    public void setTotalGastricApirateVolume(Long totalGastricApirateVolume) {
        writeProperty("totalGastricApirateVolume", totalGastricApirateVolume);
    }
    public Long getTotalGastricApirateVolume() {
        return (Long)readProperty("totalGastricApirateVolume");
    }

    public void setVomit(Boolean vomit) {
        writeProperty("vomit", vomit);
    }
    public Boolean getVomit() {
        return (Boolean)readProperty("vomit");
    }

    public void setVomitVolume(Long vomitVolume) {
        writeProperty("vomitVolume", vomitVolume);
    }
    public Long getVomitVolume() {
        return (Long)readProperty("vomitVolume");
    }

    public void setToAssesmentandplan(Assesmentandplan toAssesmentandplan) {
        setToOneTarget("toAssesmentandplan", toAssesmentandplan, true);
    }

    public Assesmentandplan getToAssesmentandplan() {
        return (Assesmentandplan)readProperty("toAssesmentandplan");
    }


}
