# To change this template, choose Tools | Templates
# and open the template in the editor.
AnPSerialized=<Assesmentandplan type="au.org.alfred.icu.nutrition.persistence.Assesmentandplan">\
<activityFactor type="java.lang.Double">0.0</activityFactor>\
<adjustedCalcMethod type="java.lang.String">none</adjustedCalcMethod>\
<adjustedWeight type="java.lang.Long">0</adjustedWeight>\
<admId type="java.lang.String">0000</admId>\
<assesmentDate type="java.util.Date">2012-01-31 18:22:17 EST</assesmentDate>\
<assesmentDietician type="java.lang.String">miguel</assesmentDietician>\
<eNComment type="java.lang.String">none</eNComment>\
<eNFormula type="java.lang.String">none</eNFormula>\
<eNHoursFeed type="java.lang.Long">0</eNHoursFeed>\
<eNPumpBE type="java.lang.String">none</eNPumpBE>\
<eNTarget type="java.lang.Long">0</eNTarget>\
<equation type="java.lang.String">none</equation>\
<heightCm type="java.lang.Long">0</heightCm>\
<heightEstimateOrActual type="java.lang.Boolean">true</heightEstimateOrActual>\
<heightSource type="java.lang.String">none</heightSource>\
<iCUAdmId type="java.lang.String">none</iCUAdmId>\
<oralDietCode type="java.lang.String">none</oralDietCode>\
<oralEstimateEnergy type="java.lang.Long">0</oralEstimateEnergy>\
<oralEstimateProtein type="java.lang.Long">0</oralEstimateProtein>\
<oralSupplements type="java.lang.String">none</oralSupplements>\
<pNComment type="java.lang.String">none</pNComment>\
<pNFormula type="java.lang.String">none</pNFormula>\
<pNHoursFeed type="java.lang.Long">0</pNHoursFeed>\
<pNPumpBE type="java.lang.String">none</pNPumpBE>\
<pNTargetRate type="java.lang.Long">0</pNTargetRate>\
<progressToDateHistory type="java.lang.String">none</progressToDateHistory>\
<proteinRequirement type="java.lang.Double">0.0</proteinRequirement>\
<referenceRange type="java.lang.String">none</referenceRange>\
<rmr type="java.lang.Integer">0</rmr>\
<stressFactor type="java.lang.Double">0.0</stressFactor>\
<ur type="java.lang.String">none</ur>\
<weight type="java.lang.Long">0</weight>\
<weightEstimateOrActual type="java.lang.Boolean">true</weightEstimateOrActual>\
<weightSource type="java.lang.String">none</weightSource>\
</Assesmentandplan>