# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
cerner_path=smb://alfapps01/apps/ICUApps/CernerDischarge/
tmp_pdf_path=/opt/glassfish3/glassfish/domains/domain1/applications/ICUDischargeSummaryWeb/pdf_tmp/
tmp_pdf_nutrition=/opt/glassfish3/glassfish/domains/domain1/applications/NutritionWeb/pdf_tmp/
cerner_user=desousami
cerner_user_pwd=bkdr4ICUm3k
cerner_user_domain=BAYSIDEHEALTH
